# Generated by Django 3.0.3 on 2020-06-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internet_connect',
            field=models.CharField(default='移动蜂窝网络', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='protocol',
            field=models.CharField(default='MQTT', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='system',
            field=models.CharField(default='无', max_length=20),
        ),
    ]
